language: go
go:
  - 1.x
  - tip
install:
  - go mod download
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
matrix:
  allow_failures:
  - go: tip
