language: go
go:
  - 1.x
  - tip
install:
  - go mod download
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
